# Generated by Django 6.0.2 on 2026-02-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_product_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCart',
            new_name='CartProduct',
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store_app.subcategory'),
        ),
    ]
