# Generated by Django 6.0.2 on 2026-02-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_rename_productcart_cartproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
