# Generated by Django 6.0.2 on 2026-02-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_alter_cartproduct_options_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение подкатегории'),
        ),
    ]
