# Generated by Django 6.0.2 on 2026-02-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_alter_category_image_alter_subcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
